{{- if $.Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $.Chart.Name }}-{{ $.Values.app }}"
  labels:
    app: {{ $.Values.app }}
  {{- with $.Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $.Values.ingress.hostname | default "" }}
    http:
      paths:
      - pathType: Prefix
        path: {{ $.Values.ingress.path }}
        backend:
          service:
            name: "{{ $.Chart.Name }}-{{ $.Values.app }}"
            port:
              number: {{ $.Values.service.port }}
{{- end }}