apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-{{ $.Values.app }}"
  labels:
    app: {{ $.Values.app }}
spec:
  type: {{ $.Values.service.type }}
  selector:
    app: {{ $.Values.app }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.deployment.ports.app }}
      protocol: {{ $.Values.service.protocol | default "TCP" }}
      {{- if $.Values.service.nodePortapp }}
      nodePort: {{ $.Values.service.nodePortapp }}
      {{- end }}
      name: "{{ $.Chart.Name }}"